### PR TITLE
Add default and configurable list of allowed languages and countries

### LINKED ISSUE #296: Release groups detected as country or languages
```
+-------------------------------------------------------+
+                   GuessIt 2.0.5                       +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
```

Everytime that a release name ends with a `-XX` and XX is part of `tlds-alpha-by-domains.txt`, the release group is not properly guessed and a wrong country/language is chosen.

Here is a list of them:
- `AR`
- `CS`
- `DR`
- `MC`
- `NA`
- `NL`
- `TL`
- `YT`

And some examples:

```
guessit "My.Name.Is.Earl.S01-S04.DVDRip.XviD-AR"
For: My.Name.Is.Earl.S01-S04.DVDRip.XviD-AR
GuessIt found: {
    "title": "My Name Is Earl", 
    "season": [
        1, 
        4
    ], 
    "format": "DVD", 
    "video_codec": "XviD", 
    "language": "Arabic", 
    "type": "episode"
}
```

```
guessit "American.Dad.S01E01.Pilot.DVDRip.x264-CS"
For: American.Dad.S01E01.Pilot.DVDRip.x264-CS
GuessIt found: {
    "title": "American Dad", 
    "season": 1, 
    "episode": 1, 
    "episode_title": "Pilot", 
    "episode_details": "Pilot", 
    "format": "DVD", 
    "video_codec": "h264", 
    "language": "Czech", 
    "type": "episode"
}
```

```
guessit Black.Sails.S01E01.HDTV.XviD.HebSubs-DR
For: Black.Sails.S01E01.HDTV.XviD.HebSubs-DR
GuessIt found: {
    "title": "Black Sails", 
    "season": 1, 
    "episode": 1, 
    "format": "HDTV", 
    "video_codec": "XviD", 
    "subtitle_language": "Hebrew", 
    "type": "episode"
}
```

```
guessit The.West.Wing.S04E06.Game.On.720p.WEB-DL.AAC2.0.H.264-MC
For: The.West.Wing.S04E06.Game.On.720p.WEB-DL.AAC2.0.H.264-MC
GuessIt found: {
    "title": "The West Wing", 
    "season": 4, 
    "episode": 6, 
    "episode_title": "Game On", 
    "screen_size": "720p", 
    "format": "WEB-DL", 
    "audio_codec": "AAC", 
    "audio_channels": "2.0", 
    "video_codec": "h264", 
    "country": "MONACO", 
    "type": "episode"
}
```

```
guessit 12.Monkeys.S02E05.1080p.WEB-DL.DD5.1.H.264-NA
For: 12.Monkeys.S02E05.1080p.WEB-DL.DD5.1.H.264-NA
GuessIt found: {
    "title": "12 Monkeys", 
    "season": 2, 
    "episode": 5, 
    "screen_size": "1080p", 
    "format": "WEB-DL", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "language": "Nauru", 
    "type": "episode"
}
```

```
guessit American.Crime.S01E02.1080p.WEB-DL.DD5.1.H.264-NL
For: American.Crime.S01E02.1080p.WEB-DL.DD5.1.H.264-NL
GuessIt found: {
    "title": "American Crime", 
    "season": 1, 
    "episode": 2, 
    "screen_size": "1080p", 
    "format": "WEB-DL", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "language": "Dutch", 
    "type": "episode"
}
```

```
guessit Better.Call.Saul.S02.720p.HDTV.x264-TL
For: Better.Call.Saul.S02.720p.HDTV.x264-TL
GuessIt found: {
    "title": "Better Call Saul", 
    "season": 2, 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "language": "Tagalog", 
    "type": "episode"
}
```

```
guessit 60.Minutes.2008.12.14.HDTV.XviD-YT
For: 60.Minutes.2008.12.14.HDTV.XviD-YT
GuessIt found: {
    "title": "60 Minutes", 
    "year": 2008, 
    "episode_title": "12 14", 
    "format": "HDTV", 
    "video_codec": "XviD", 
    "country": "MAYOTTE", 
    "type": "movie"
}
```

### LINKED ISSUE #458: Wrong format guess
For the Czech scene release group `SDTV`, the group name is used as a source too. The source in this case is `HDTV`
```
$ guessit Goof.Troop.1x24.Waste.Makes.Haste.720p.HDTV.x264.CZ-SDTV
For: Goof.Troop.1x24.Waste.Makes.Haste.720p.HDTV.x264.CZ-SDTV
GuessIt found: {
    "title": "Goof Troop",
    "season": 1,
    "episode": 24,
    "episode_title": "Waste Makes Haste",
    "screen_size": "720p",
    "format": [
        "HDTV",
        "TV"
    ],
    "video_codec": "h264",
    "language": "Czech",
    "type": "episode"
}
```

### PR DESCRIPTION
**Pull request by ratoaq2**
Fixes #296 
- Added a pre-defined list for common languages and countries in options.json
- Enhanced test to cover all scenarios
- Since dutch (NL) is a common language to match NLSubs, but it's also a release_group: NL, ~~ConflictingReleaseGroup rule was implemented. That might also fix #458~~
- Improved release group detection to properly detect dash-separated release groups. It fixes #458 and #196
- Allow empty language/country list. If user specify `--no-embedded-config`, the language and country list will be empty which disables language and country detection.
- Added Swiss German / Flemish scenarios from #462

### CODE REVIEW

**Comment by ratoaq2** [comment]
OK, now it fixes #458 as well

**Comment by ratoaq2** [comment]
This PR got too big. Sorry for that.

All cases for #258 and #259 should be covered, except these:
`ElegantRaw.15.12.30.Zorah.White.Zorah.Gets.A.Lesson.In.French.XXX.1080P.MP4-GUSH`
`Playboy Nederland January 2016-PL`

The idea in this PR is to have a default limited set of detected languages that could be entirely disabled (`--no-embedded-config`) or extended by the user's configuration/options.

The open points are:
- Is this a good way to go?
- Should we add an explicit option to disable language/country detection instead of using the embedded config option?
- What to do with the remaining corner cases? Probably nothing. But should we add an option to enable/disable detection by name? e.g.: We want to match `ABC-en-fr`, but we don't want to match `Lesson.In.French`, but we still want to match `TrueFrench`

The added test cases can show how this PR behaving to have a reference for discussion.

**Comment by ratoaq2** [comment]
@Toilal,
I'm planning to merge all the open PR in guessit. Some of them are quite straight forward. But for this one and #484 I would like to get some feedback from you: if you think that's a good solution or not.

**Comment by Toilal** [comment]
I'll have a look to code tonight, but having this feature definitively worth it, it'll be great 😀. Thanks.

**Pull request merged**
