### PR TITLE
Proposal for #365: Deprecate 'format' in favor of 'source' property

### PR DESCRIPTION
**Pull request by ratoaq2**
TODO list:
- [x] Update tests with the new `source` property
- [x] Update docs with migration path from 2.x to 3.x (`format` removal)
- [x] Final agreement on proper naming
- [x] Suggestions

This is an initial proposal to make `format` more consistent: #365 
Initially I though about making the `source` property less enigmatic than `format`, so it uses natural language instead of labels. But on the other hand, to be more user-friendly means less api-friendly. This is an open point that I would like feedback (including if the values should or shouldn't have spaces)

This is the current source list:

- `Analogue HDTV`
- `Blu-ray`
- `Camera`
- `Digital TV`
- `DVD`
- `HD Camera`
- `HD Telecine`
- `HD Telesync`
- `HD-DVD`
- `HDTV`
- `Pay-per-view`
- `Satellite`
- `Telecine`
- `Telesync`
- `TV`
- `Ultra HDTV`
- `VHS`
- `Video on Demand`
- `Web`
- `Workprint`

On the functional side, the `Rip` part is captured in the `other` property. Together with some variations: ~~`Capped` (e.g.: WEBCAP) and~~ `ReEncoded` (BRRip comes from a ReEncode of a BluRay Release)

Here's a full list of examples (Updated on 31.05.2017 23:00 CEST):
```
For: AHDTV
GuessIt found: {
    "source": "Analogue HDTV", 
    "type": "movie"
}
For: BD
GuessIt found: {
    "source": "Blu-ray", 
    "type": "movie"
}
For: BD25
GuessIt found: {
    "source": "Blu-ray", 
    "type": "movie"
}
For: BD5
GuessIt found: {
    "source": "Blu-ray", 
    "type": "movie"
}
For: BD50
GuessIt found: {
    "source": "Blu-ray", 
    "type": "movie"
}
For: BD9
GuessIt found: {
    "source": "Blu-ray", 
    "type": "movie"
}
For: BDRIP
GuessIt found: {
    "source": "Blu-ray", 
    "other": "Rip", 
    "type": "movie"
}
For: BLURAY
GuessIt found: {
    "source": "Blu-ray", 
    "type": "movie"
}
For: BLURAYRIP
GuessIt found: {
    "source": "Blu-ray", 
    "other": "Rip", 
    "type": "movie"
}
For: BRRIP
GuessIt found: {
    "source": "Blu-ray", 
    "other": [
        "ReEncoded", 
        "Rip"
    ], 
    "type": "movie"
}
For: BRSCR
GuessIt found: {
    "source": "Blu-ray", 
    "other": [
        "ReEncoded", 
        "Screener"
    ], 
    "type": "movie"
}
For: BRSCREENER
GuessIt found: {
    "source": "Blu-ray", 
    "other": [
        "ReEncoded", 
        "Screener"
    ], 
    "type": "movie"
}
For: CAM
GuessIt found: {
    "source": "Camera", 
    "type": "movie"
}
For: CAMRIP
GuessIt found: {
    "source": "Camera", 
    "other": "Rip", 
    "type": "movie"
}
For: DSR
GuessIt found: {
    "source": "Satellite", 
    "type": "movie"
}
For: DSRIP
GuessIt found: {
    "source": "Satellite", 
    "other": "Rip", 
    "type": "movie"
}
For: DSRRIP
GuessIt found: {
    "source": "Satellite", 
    "other": "Rip", 
    "type": "movie"
}
For: DTH
GuessIt found: {
    "source": "Satellite", 
    "type": "movie"
}
For: DTHRIP
GuessIt found: {
    "source": "Satellite", 
    "other": "Rip", 
    "type": "movie"
}
For: DVB
GuessIt found: {
    "source": "Digital TV", 
    "type": "movie"
}
For: DVBRIP
GuessIt found: {
    "source": "Digital TV", 
    "other": "Rip", 
    "type": "movie"
}
For: DVD
GuessIt found: {
    "source": "DVD", 
    "type": "movie"
}
For: DVD5
GuessIt found: {
    "source": "DVD", 
    "type": "movie"
}
For: DVD9
GuessIt found: {
    "source": "DVD", 
    "type": "movie"
}
For: DVDR
GuessIt found: {
    "source": "DVD", 
    "type": "movie"
}
For: DVDRIP
GuessIt found: {
    "source": "DVD", 
    "other": "Rip", 
    "type": "movie"
}
For: HDCAM
GuessIt found: {
    "source": "HD Camera", 
    "type": "movie"
}
For: HDCAMRIP
GuessIt found: {
    "source": "HD Camera", 
    "other": "Rip", 
    "type": "movie"
}
For: HDDVD
GuessIt found: {
    "source": "HD-DVD", 
    "type": "movie"
}
For: HDDVDRIP
GuessIt found: {
    "source": "HD-DVD", 
    "other": "Rip", 
    "type": "movie"
}
For: HDRIP
GuessIt found: {
    "other": [
        "HD", 
        "Rip"
    ], 
    "type": "movie"
}
For: HDTC
GuessIt found: {
    "source": "HD Telecine", 
    "type": "movie"
}
For: HDTCRIP
GuessIt found: {
    "source": "HD Telecine", 
    "other": "Rip", 
    "type": "movie"
}
For: HDTS
GuessIt found: {
    "source": "HD Telesync", 
    "type": "movie"
}
For: HDTSRIP
GuessIt found: {
    "source": "HD Telesync", 
    "other": "Rip", 
    "type": "movie"
}
For: HDTV
GuessIt found: {
    "source": "HDTV", 
    "type": "movie"
}
For: HDTVRIP
GuessIt found: {
    "source": "HDTV", 
    "other": "Rip", 
    "type": "movie"
}
For: PDTV
GuessIt found: {
    "source": "Digital TV", 
    "type": "movie"
}
For: PDTVRIP
GuessIt found: {
    "source": "Digital TV", 
    "other": "Rip", 
    "type": "movie"
}
For: PPV
GuessIt found: {
    "source": "Pay-per-view", 
    "type": "movie"
}
For: PPVRIP
GuessIt found: {
    "source": "Pay-per-view", 
    "other": "Rip", 
    "type": "movie"
}
For: RIPSDTV
GuessIt found: {
    "other": "Rip", 
    "source": "TV", 
    "type": "movie"
}
For: RIPTV
GuessIt found: {
    "other": "Rip", 
    "source": "TV", 
    "type": "movie"
}
For: SATRIP
GuessIt found: {
    "source": "Satellite", 
    "other": "Rip", 
    "type": "movie"
}
For: SDTV
GuessIt found: {
    "source": "TV", 
    "type": "movie"
}
For: SDTVRIP
GuessIt found: {
    "source": "TV", 
    "other": "Rip", 
    "type": "movie"
}
For: TC
GuessIt found: {
    "source": "Telecine", 
    "type": "movie"
}
For: TCRIP
GuessIt found: {
    "source": "Telecine", 
    "other": "Rip", 
    "type": "movie"
}
For: TELECINE
GuessIt found: {
    "source": "Telecine", 
    "type": "movie"
}
For: TELECINERIP
GuessIt found: {
    "source": "Telecine", 
    "other": "Rip", 
    "type": "movie"
}
For: TELESYNC
GuessIt found: {
    "source": "Telesync", 
    "type": "movie"
}
For: TELESYNCRIP
GuessIt found: {
    "source": "Telesync", 
    "other": "Rip", 
    "type": "movie"
}
For: TS
GuessIt found: {
    "source": "Telesync", 
    "type": "movie"
}
For: TSRIP
GuessIt found: {
    "source": "Telesync", 
    "other": "Rip", 
    "type": "movie"
}
For: TVRIP
GuessIt found: {
    "source": "TV", 
    "other": "Rip", 
    "type": "movie"
}
For: TVRIPHD
GuessIt found: {
    "source": "HDTV", 
    "other": "Rip", 
    "type": "movie"
}
For: UHDRIP
GuessIt found: {
    "source": "Ultra HDTV", 
    "other": "Rip", 
    "type": "movie"
}
For: UHDTV
GuessIt found: {
    "source": "Ultra HDTV", 
    "type": "movie"
}
For: VHS
GuessIt found: {
    "source": "VHS", 
    "type": "movie"
}
For: VHSRIP
GuessIt found: {
    "source": "VHS", 
    "other": "Rip", 
    "type": "movie"
}
For: VIDEOTS
GuessIt found: {
    "source": "DVD", 
    "type": "movie"
}
For: VOD
GuessIt found: {
    "source": "Video on Demand", 
    "type": "movie"
}
For: VODRIP
GuessIt found: {
    "source": "Video on Demand", 
    "other": "Rip", 
    "type": "movie"
}
For: WEB
GuessIt found: {
    "source": "Web", 
    "type": "movie"
}
For: WEBCAP
GuessIt found: {
    "source": "Web", 
    "other": "Rip", 
    "type": "movie"
}
For: WEBCAPRIP
GuessIt found: {
    "source": "Web", 
    "other": "Rip", 
    "type": "movie"
}
For: WEBDL
GuessIt found: {
    "source": "Web", 
    "type": "movie"
}
For: WEBDLRIP
GuessIt found: {
    "source": "Web", 
    "other": "Rip", 
    "type": "movie"
}
For: WEBHD
GuessIt found: {
    "source": "Web", 
    "type": "movie"
}
For: WEBRIP
GuessIt found: {
    "source": "Web", 
    "other": "Rip", 
    "type": "movie"
}
For: WORKPRINT
GuessIt found: {
    "source": "Workprint", 
    "type": "movie"
}
For: WP
GuessIt found: {
    "source": "Workprint", 
    "type": "movie"
}
```

~~An important note: this is NOT a breaking change :-)~~

@Toilal your feedback is really important on this. I'm not planning to rush on this topic, so I appreciate whenever you have free time to take a proper look at this one.

Updates on 30.05.2017 19:50 CEST:
- Add HD Camera/Telecine/Telesync.
- Rename PPV to Pay-per-view.
- Fix wrong HDRip detection.
- WEBCap is a synonym to WEBRip

Updates on 31.05.2017 23:00 CEST:
- Dropped `format` property
- Added `source` to all tests
- Renamed `BluRay` to `Blu-ray`

Updates on 01.06.2017 22:30 CEST:
- Renamed `WEB` to `Web`

### CODE REVIEW

**Comment by Toilal** [comment]
@ratoaq2 I'm currently preparing the 2.1.3 release.

As next changes are breaking for end users, I think we should go for 3.x releases after this one. There will be no 2.2 version at all. I'll rename the milestones in github.

**Comment by Toilal** [comment]
@ratoaq2 I've released `2.1.3`, and next version will be `3.0.0` so it's time to go for breaking changes, and we must perform all of them before releasing.

I'm ok with changes from this pull request, but we could also remove the `format` property as we are going for a major release.

Issues to fix before releasing are here : https://github.com/guessit-io/guessit/milestone/12

**Comment by ratoaq2** [comment]
Great. And what about having or not spaces in the value? `Ultra HDTV`, `UltraHDTV` or `UHDTV`

I think it's a good opportunity to have consistency across all values. There aren't so many inconsistencies, but still we can find some in some properties. I can remember some in `other` property:
`PS Vita`, `DualAudio`, `ReEncoded`, `UltraHD`, `Read NFO`. 

I personally like to have a user friendly output, you don't need to be an expert to understand the guessit result. But I'm not totally convinced when thinking api usage.

**Comment by Toilal** [comment]
I'm in favor of spaces in values, there should be no camel case at all.

Also acronyms should be used only when it's really obvious for anybody to
understand them.

**Comment by Toilal** [comment]
I've check the actual samples, and it seems really good to me. 

`WEB` should be `Web` as it's not an acronym though.

I really like the extract of `Rip` into `other` property, making sources really consistent. It should help many app relying on guessit to classify videos. Thanks :+1:

**Comment by ratoaq2** [comment]
Thanks, I also liked the final result. I believe it's already in a good shape to be merged to develop. We can still change it if needed until 3.0 release

**Comment by ratoaq2** [comment]
This PR is completed from my perspective. Feel free to review or merge it.

**Comment by labrys** [comment]
@Toilal My 2-cents on the acronyms - I think that for api-usage using acronyms for consistent style across attributes and for simpler string-processing makes sense.  A simple mapping could be provided to convert the acronyms to sensible UI defaults.  For example:

**Comment by ratoaq2** [comment]
It's a fair comment.
I was brainstorming a lot on this topic. There we several possibilities that came up, some that I liked most, some that I dislike:
- Instead of returning strings for them, return a `Value` object which has `key` and `value` (or `value` and `description` - or - `acronym` and `value`) and behaves like `babelfish.Language`/`babelfish.Country`
- Add an option to guessit to switch on/off `acronyms`, so it returns user-friendly or api-friendly values (probably the `Match` object would need an extension to have the additional field)

I know that guessit has an advanced flag to return `Match` objects, but the raw value might not represent the acronym itself.

As an api-user of guessit, I must agree that having an `acronym-style` option would be a better fit.
As a regular user, I don't want to dig in the internet and forums to discover that `DDC` is  actually `Director's Definitive Cut`

I don't want to rush with this PR or with issue #459 without proper discussions and feedback with different points of view

**Comment by Toilal** [comment]
I would say a good API should provide values ready to display for end user. That's a design rule I try to apply for each API I have to develop in my job, and guessit should also match this.

CLI is also often used for debugging/testing purpose, so output should be consistent between CLI and API.

Adding a mapping between "display values" and "API values" would add more complexity, I don't want to maintain and document such a mapping. Same for options mentionned by @ratoaq2, it would still require more docs and maintenance, and I don't think it worth the small inconvenience of having user values output in guessit API.

**Comment by labrys** [comment]
@Toilal I'm fine with using longer attribute names or any other consistent naming convention, i just suggested the acronym as an option for consistency.  

As for an API providing values ready for end usage, I mostly agree except that an api is more for programming, not for a UI.  Without spaces in a tag, and with tags being consistently lower-case, it lends itself better to programming.  For example in the future tags could be extended to have attribute-like behaviour (e.g. `if guess.source.bluray:`)

**Comment by ratoaq2** [comment]
Just playing the devil's advocate... 
I do agree up to the part of accessing keys as attributes. That could be a natural enhancement of guessit api. But accessing values as attributes are questionable:

You won't use `guess.screen_size.1080p` because it's an invalid attribute name: although it's lowercase and without spaces. And it doesn't make sense to change guessit returned values to be valid python attributes: `screen_size: '_1080p'`

You would rather use : `if guess.screen_size == '1080p'`
Or
`if guess.source == 'Blu-ray' `

**Comment by labrys** [comment]
With default collections you can't do `if guess.screen_size == '1080p'`.  You would have to do `if '1080p' in guess.screen_size`.  Also with text-based labels instead of attributes, if a name changed in a future guessit release, the text based label would still keep plugging away with no obvious indication of error.  With an attribute, it would give a definitive error showing the attribute is invalid.  I'm not saying attribute access should replace current behaviour, it should complement it.

**Comment by ratoaq2** [comment]
Going back to this PR and trying to keep the scope and focus on it. I'm pretty happy with the current state using a more readable set of values. 

I still see room for enhancement to allow users to configure and tweak advanced settings in guessit (like discussed here https://github.com/guessit-io/guessit/issues/342#issuecomment-305104324 ). I see no problem to only provide and support one set of values that are human readable, but still allow user to define and use its own set of values, like in his advanced configuration settings.

**Pull request merged**
