### PR TITLE
Add Input filename passthrough for CLI tool

### PR DESCRIPTION
**Pull request by pR0Ps**
Passing the input filename through to the output allows consumers of the `guessit` command output to grab the filename directly in the same way as other properties. This is especially helpful when processing multiple filenames and iterating over the results.

Example:
```bash
guessit --json *.mkv | jq -r '"\(.raw_input):\(.title):\(.season):\(.episode)"' | \
while IFS=':' read -r filename show season episode; do
    echo "Processing $filename --> $show - S${season}E${episode}"
    # actually process the file
done
```

The `raw_input` key was only added when running the CLI tool since code that uses `guessit` as a library won't need this functionality.

### CODE REVIEW

**Comment by Toilal** [comment]
I like the idea, but I want to make it optional.

**Comment by Toilal** [comment]
Thanks. it's been merged manually.

**Comment by Toilal** [comment]
(With some changes)

**Comment by pR0Ps** [comment]
Thanks for taking care of this!

**Pull request closed without merging**
