### PR TITLE
Add support for "Hybrid" and "iT"

### PR DESCRIPTION
**Pull request by plotski**
This adds support for the `Hybrid` tag and adds it to `other`.

### CODE REVIEW

**Comment by plotski** [comment]
The "iT" tests are already tested but the tests aren't picked up by pytest because "streaming_services.yaml" should be named "streaming_services.yml".

I don't know if that's intentional, and 25 of those streaming service tests fail, which should probably be addressed in a different commit.

I try and fix the failing tests if you want. Let me know.

**Comment by Toilal** [comment]
`iT` should be guessed only if it match case, as it's a too short and common word and may conflict with other meanings.

**Comment by Toilal** [comment]
Thanks. It's in current HEAD :)

**Comment by plotski** [comment]
How would this be done? It looks like I can use regular expressions by using the
"re:" prefix, but there isn't any to force case-sensitivity (the opposite of
"(?i:...)"). Is using regular expressions enough to enable case-sensitivity?

And what about the disabled streaming service tests? Was this a mistake or are
they disabled intentionally?

**Comment by plotski** [comment]
Looks like this was more work for you than it was for me.
So thank you! :)

**Pull request closed without merging**
