### PR TITLE
SxxExx pattern should be preferred over weak matches

### LINKED ISSUE #396: Wrong guess
If the filename is named weirdly then it really throws off guessit.

```
➜  ~ guessit "Zoo.S02E05.1080p.WEB-DL.DD5.1.H.264.HKD/160725_02.mkv"
For: Zoo.S02E05.1080p.WEB-DL.DD5.1.H.264.HKD/160725_02.mkv
GuessIt found: {
    "title": "Zoo", 
    "season": 2, 
    "screen_size": "1080p", 
    "format": "WEB-DL", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "HKD", 
    "episode": 2, 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

### PR DESCRIPTION
**Pull request by ratoaq2**
Fixes #396

- If multiple season/episodes matches are found with different values, keep the one tagged as 'SxxExx' or in the rightmost filepart.

### CODE REVIEW

**Comment by ratoaq2** [comment]
This actually fixes #398 as well

**Comment by ratoaq2** [comment]
And it also fixes #399 (except the files with backwards title)

**Comment by ratoaq2** [comment]
It also fixes the backwards scenarios: #394 and #399

**Comment by Toilal** [comment]
@ratoaq2 Sorry I don't have time for now to help on guessit, but feel free to merge what you think is good for guessit :)

**Pull request merged**
