### PR TITLE
Add additional Streaming Services

### PR DESCRIPTION
**Pull request by duramato**
This PR adds the following streaming services:

- TV4 Sweeden
- RTÉ One
- TLC
- USA Network
- NBC
- TV3 Ireland
- AMC
- DIY Network
- Investigation Discovery

### CODE REVIEW

**Comment by Toilal** [comment]
It seems there's something wrong with Python 2.

**Comment by ratoaq2** [comment]
The issue is with `é` character. 

I haven't tried this branch, so I still can't tell a way to fix that. But probably it would be a better idea to avoid accented characters. Any opinions on this?

**Comment by Toilal** [comment]
I just fix the issue in testing framework causing the build to fail on python 2.

I'll rebase and merge, thanks !

**Comment by Toilal** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
