### PR TITLE
Enhance expected_title and expected_group

### LINKED ISSUE #376: Enhance expected_title and expected_group
Series and movies names that contains numbers might confuse guessit.

```
guessit "The.100.Season.1.Complete"
For: The.100.Season.1.Complete
GuessIt found: {
    "title": "The", 
    "season": 1, 
    "episode": 0, 
    "other": "Complete", 
    "type": "episode"
}
```

An alternative is to use `expected_title` (same applies for `expected_group`), but it doesn't work as initially expected:
```
guessit -T "The 100" "The.100.Season.1.Complete"
For: The.100.Season.1.Complete
GuessIt found: {
    "title": "The", 
    "season": 1, 
    "episode": 0, 
    "other": "Complete", 
    "type": "episode"
}
```

An alternative is to use the exact string or regex, but the guessed title is not properly formatted.
```
guessit -T "re:The 100" "The.100.Season.1.Complete"
For: The.100.Season.1.Complete
GuessIt found: {
    "title": "The.100", 
    "season": 1, 
    "other": "Complete", 
    "type": "episode"
}
```
```
guessit -T "The_100" "The_100_Season_1_Complete"
For: The_100_Season_1_Complete
GuessIt found: {
    "title": "The_100", 
    "season": 1, 
    "other": "Complete", 
    "type": "episode"
}
```

My proposal is to enhance `expected_title` and `expected_group` for string matches.
The expected title/group input string could be used to generate a regex pattern to match the title/group and use the title/group itself as the match value:
`-T "The 100"` could generate a regex equivalent to `'re:(?<![\W_])The +100(?=[\W_]|$)'`, but the `match.value` is `The 100`
```
guessit -T "The 100" "The_100_Season_1_Complete"
For: The_100_Season_1_Complete
GuessIt found: {
    "title": "The 100", 
    "season": 1, 
    "other": "Complete", 
    "type": "episode"
}
```

I have an utility function that generates a regex pattern for a given expected title (it handles titles with `'` and `:` as well):
```
def prepare(string):
    """Prepare a string to be used as a regex in guessit expected_title.

    :param string:
    :type string: str
    :return:
    :rtype: str
    """
    # replace some special characters with space
    characters = {'-', '.', ',', '*', '(', ')'}
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)

    # replace unicode characters with period
    string = re.sub(r'[^\x00-\x7F]+', '.', string)

    # escape other characters that might be problematic
    string = re.escape(string)

    # dots (the replacement of unicode characters) shouldn't be escaped and should match 1 or more characters
    string = string.replace('\.', '.+')

    # ' should be optional
    string = string.replace(r"\'", r"'?")

    # spaces shouldn't be escaped
    string = string.replace('\ ', ' ')

    # replace multiple spaces with one
    string = re.sub(r'\s+', ' +', string.strip())

    # : should be optional or space
    string = string.replace(r"\:", r" ?")

    return r're:(?<![\W_]){name}(?=[\W_]|$)'.format(name=string)
```

IMO, this feature could simplify guessit configuration file for `expected_title` or `expected_group` as proposed in #374

### PR DESCRIPTION
**Pull request by Toilal**
Close #376

@ratoaq2, please test this fork and merge if it's OK for you.

### CODE REVIEW

**Comment by ratoaq2** [comment]
That one was fast.

All my test scenarios seem to work fine with this implementation. Except one:

```
guessit -T '11.22.63' "/11.22.63/Season 1/11.22.63.106.hdtv-abc"
For: /11.22.63/Season 1/11.22.63.106.hdtv-abc
GuessIt found: {
    "title": "11 22 63", 
    "season": 1, 
    "episode": 6, 
    "format": "HDTV", 
    "release_group": "abc", 
    "type": "episode"
}
```

Given that I provided the expected title as `11.22.63`, the expected title was `11.22.63`, not `11 22 63`
I wonder if there's an easy way to control the `match.value` to always be the actual value defined by the user/caller. Waiting your feedback, otherwise we can leave this scenario outside of the scope of this PR since we already have a big improvement here.

**Comment by ratoaq2** [comment]
It worked using:
```
            else:
                value = search
                for sep in seps:
                    input_string = input_string.replace(sep, ' ')
                    search = search.replace(sep, ' ')
                for start in find_all(input_string, search, ignore_case=True):
                    ret.append({'start': start, 'end': start + len(search), 'value': value})
```
```
? /11.22.63/Season 1/11.22.63.106.hdtv-abc
: options: -T 11.22.63
  title: 11.22.63
  season: 1
  episode: 6
  format: HDTV
  release_group: abc
  type: episode
```

And one small thing as well, probably both `title` and `release_group` should have `validator=seps_surround`.
Imagine small words release groups like `DHD` or a title like `The Second`  but the release name is `The Secondary.S01....`

**Comment by Toilal** [comment]
What about deprecating `re:` prefix support, and only use the string search, but with proposed fixes ? It seems to cover every case I think.

I'll add some comit with your latest comment.

**Comment by ratoaq2** [comment]
I'm not sure about deprecating `re:` prefix.

I'm still waiting to check how is the behavior for real scenarios where the series/movie contains `:` or `'` in its name. Releases with `:` or `'`, the expected title might help guiding to the correct title
expected: Marvel's Abc
release_name: Marvels.abc.s01e02

expected: Show Name: Super Show
release_name: show.name.super.show

And the regex might help to get rid of some inconsistencies. Let's get a real issue #358: 
`This.is.Us.S01E01.HDTV.x264-KILLERS.mkv`, I could provide a regex to avoid specifying every single show that might lead to this issue. But as you said, it's just an option. The string search could handle this very same issue as well.

**Comment by Toilal** [comment]
Ok ! Then I'll merge this pull request.

For `This.is.Us`, this is a complex case ... Problem is that some shows like `Shameless.US` are supposed to be parsed as `title: Shameless`, `country: US`. 

To fix this issue properly, we should have some kind of grammatical analysis of the title ...

**Comment by OmgImAlexis** [comment]
@Toilal I've noticed most shows like this have a uppercase U and a lowercase s whereas ones that're meaning the country have both capitalised.

**Comment by duramato** [comment]
IMO that can't be set rule a release name string can be all lower case and/or all uppper case. The release name would still be the same.

**Comment by Toilal** [comment]
I agree we can't rely on case to implement the rules.

**Comment by OmgImAlexis** [comment]
Could you not rely on case for preference when there's no clear "winner" so to speak?

**Comment by shlomiLan** [comment]
Is it possible to check if there is a show with that name in TVDB (or any other source)? 
For `This Is` that doesn't have a show TVDB should return `None` so you will check `This Is Us` and return it because it has a listing in TVDB and for `Shameless` because it's a valid show it will be returned as the title name.

**Pull request merged**
