### PR TITLE
Streaming Service: Add Sony

### PR DESCRIPTION
**Pull request by codyopel**
https://www.sonyliv.com/
https://www.sony.com/electronics/support/home-video-4k-ultra-hd-media-players/fmp-x10/articles/S1Q0521

### CODE REVIEW

**Comment by codyopel** [comment]
@Toilal I am not exactly sure how you want commit messages formatted to satisfy the linter

**Comment by Toilal** [comment]
You have to use conventional commits. https://www.conventionalcommits.org it helps me to automate changelog generation and semantic releases.

**Comment by Toilal** [comment]
Also, the title should not be capitalized (first lettre should be lowercase)

**Comment by codyopel** [comment]
`feat(streaming_service): add Sony`, I assume this is how it should be unless you mean to lowercase sony.  I'll recommit when I get a chance.

**Comment by codyopel** [comment]
@Toilal I have over a dozen more services to add when I get a chance.  If it makes it easier, once you get a chance to review the PRs I can merge the commits into a single branch in a new PR so you don't have to fix all the merge conflicts yourself.  I just want to open individual PRs to review the commits separately incase something needs fixing so that I can fix it before merging.

**Comment by Toilal** [comment]
Yes, no problem for all services addition in a single commit 👌

**Comment by codyopel** [comment]
See #687

**Pull request closed without merging**
